# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 13:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsitePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('category', models.TextField(choices=[('wydarzenia', 'wydarzenia'), ('informacje', 'informacje'), ('konkursy', 'konkursy'), ('wycieczki', 'wycieczki'), ('sport', 'sport')], max_length=80)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/website_posts_images/')),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
