# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_website_template', '0002_auto_20170126_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='websitepost',
            options={'verbose_name_plural': 'WebsitePosts'},
        ),
    ]
