# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_website_template', '0008_auto_20170126_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Gallery',
            },
        ),
    ]
