# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_website_template', '0009_gallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
