# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 18:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_website_template', '0011_gallery_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ImageInGallery',
        ),
    ]
