# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 21:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_website_template', '0014_gallery_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'galeria', 'verbose_name_plural': 'Galerie'},
        ),
        migrations.AlterModelOptions(
            name='imageingallery',
            options={'verbose_name': 'zdjęcie', 'verbose_name_plural': 'Zdjęcia'},
        ),
        migrations.AlterModelOptions(
            name='websitepost',
            options={'verbose_name': 'wpis', 'verbose_name_plural': 'Wpisy'},
        ),
    ]
