# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 09:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_website_template', '0015_auto_20170126_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='image',
        ),
    ]
