# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_website_template', '0016_remove_gallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageingallery',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_in_galleries', to='school_website_template.Gallery'),
        ),
    ]
