# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_website_template', '0018_auto_20170127_1059'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageInGallery',
            new_name='GalleryImage',
        ),
    ]
