# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 11:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_website_template', '0022_attachment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
