# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-30 19:01
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_website_template', '0025_auto_20170128_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websitepost',
            name='author',
        ),
        migrations.RemoveField(
            model_name='websitepost',
            name='category',
        ),
        migrations.RemoveField(
            model_name='websitepost',
            name='image',
        ),
        migrations.RemoveField(
            model_name='websitepost',
            name='title',
        ),
        migrations.RemoveField(
            model_name='websitepost',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='websitepost',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
