# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-01 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_website_template', '0026_auto_20170130_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitepost',
            name='author',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
