# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-01 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_website_template', '0027_websitepost_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitepost',
            name='title',
            field=models.CharField(default='Test', max_length=100),
            preserve_default=False,
        ),
    ]
