# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-02 17:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_website_template', '0029_websitepost_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websitepost',
            name='category',
        ),
    ]
