# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-03 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_website_template', '0030_remove_websitepost_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitepost',
            name='category',
            field=models.CharField(choices=[('wydarzenia', 'wydarzenia'), ('informacje', 'informacje'), ('konkursy', 'konkursy'), ('wycieczki', 'wycieczki'), ('sport', 'sport')], default='example', max_length=120),
            preserve_default=False,
        ),
    ]
